apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gateway-service-destination-rule
  namespace: microservices-project
spec:
  host: gateway-service.microservices-project.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s

